version: "3.9"

services:
  nestjs:
    build: .
    container_name: nest-api
    ports:
      - "${PORT:-8000}:8000"
    environment:
      PORT: 8000
      NODE_ENV: production
    restart: unless-stopped